### ISSUE TITLE
Say Goodbye to the Mac App Store

### ISSUE THREAD

**Issue by cyanzhong** [MarkEdit-app/MarkEdit#368]
Obviously, the Mac App Store is no longer somewhere I would like to stay.

There are many reasons, the most important one is that they refuse to get my name right. Also, I don't want to publish apps to some regions where I need to get a license to do so.

Since MarkEdit is an open-source project, I don't think anyone should censor my work **again and again**. I started thinking about non-MAS distributions.

Related: https://github.com/MarkEdit-app/MarkEdit/wiki/Philosophy#be-a-good-macos-citizen.

**Comment by philipp-heinrich** [comment]
Any plans to get it installable via brew instead?
