### ISSUE TITLE
QuickLook Extension can be broken by iA Writer

### ISSUE THREAD

**Issue by CosmicToast** [MarkEdit-app/MarkEdit#448]
The QuickLook extension doesn't appear to be registering when installing from GitHub.
I have it ticked in `Extensions` → `Quick Look`, but to no avail.
I took a look at `qlmanage -m plugins` to see if it got registered, and indeed there's no entry for Markdown or for MarkEdit in there.

This is on `Sonoma 14.2.1 (23C71)`.

**Comment by CosmicToast** [comment]
I've attempted the following (in no particular order, besides the last one):
* rebooting the device
* force relaunching finder
* making sure no other quick look extensions are active
* making sure there's no other MarkEdit instances, that it is running (before force relaunching finder)

None of these seem to have done anything.

**Comment by CosmicToast** [comment]
Yes, I can find MarkEdit in `System Settings > Privacy & Security > Extensions > Quick Look`.
Toggling it does nothing, including after I relaunch finder.
`PreviewExtension.appex` is present as expected, both in github release version and homebrew version.

However, there is no `MarkEdit` processes at all, unless MarkEdit (the app itself) is running.
Even then, there is no process mentioning Finder.
It doesn't show up even with the app store version.

I tested a few other extensions, and the qlmarkdown extension seems to work as expected, so it's not a general "quicklook doesn't use any extensions" problem.
There does seem to be something funny to do with markdown in particular though, since I also checked the bear quicklook extension and ttscoff's mmd-quicklook (a generator), neither of which had any noticeable effect (the latter, being a generator, didn't do anything even when invoked with qlmanage).

I honestly have no clue as to how to debug this, since it does seem like some plugins can work on the same files that fail otherwise.

**Comment by CosmicToast** [comment]
`mdls` consistently reports `net.daringfireball.markdown`.
As an additional piece of interesting information, it looks like the quicklook plugin does work on text bundle files... just not plain `.md` as per above.

**Comment by CosmicToast** [comment]
I tried to remove anything that could possibly hold the association.
To do this, I did a recursive search for `net.daringfireball.markdown` in `/Applications`, `/Library/QuickLook`, `~/Applications` and `~/Library/QuickLook`.
Anything that matched, I moved elsewhere and ensured none of it was registered anymore in any capacity.
Then I disabled and re-enabled the extension...

Same result.
The behavior is as such:
I get the MarkEdit preview for text bundles, but a "plaintext" preview for .md files.
The only hits for the UTI are MarkEdit and XCode.

Is it possible that XCode is holding the file type association?

**Comment by CosmicToast** [comment]
Funnily enough, after reading the above, I tried removing iA Writer and everything started working immediately. (I then reinstalled it and everything stayed ok, so hmm)
This does warrant closing, and I'll change the title to help any future users. :)

**Comment by ziadoz** [comment]
@cyanzhong I'm also experiencing the issue described here.

I had iA Writer Classic installed (via Rosetta) when I installed Markedit alongside it by downloading it from GitHub. 

- I've deleted iA Writer Classic and cleaned up all of the applications files and extensions it left behind. 
- I've restarted my machine and relaunched Finder multiple times. 
- The QuickLook extension appears registered in System Preferences, and looks to be running Activity Monitor. 
- I've also checked `mdls` and it recognises the file as `kMDItemContentType = app.markedit.md`.
- I have Sublime Text installed (not sure if this is relevant, but I saw it mentioned).

Previews looks like this:

<img width="812" alt="image" src="https://github.com/MarkEdit-app/MarkEdit/assets/645637/480ad188-e201-4c12-a757-12704545128b">

**Comment by ziadoz** [comment]
> I checked the crash log and there's nothing worth investigating, they are all system logs.

Oh ok. Well thanks for taking a look anyway. I ended up uninstalling MarkEdit because System Preferences just wouldn't open with it installed (presumably due to the preview extension).

**Comment by ziadoz** [comment]
@cyanzhong Yes I have that option enabled already. The MarkEdit app opens and works fine, it's just the preview extension which wasn't working. 

It's the actual System Preferences app that doesn't work once the app is installed. I click the System Preferences icon, it appears in the dock, but there's no app window. Eventually it crashes, and I found that log matching the timestamp above. Uninstalling MarkEdit and all its files using AppCleaner was the only thing that got System Preferences working again. It's very weird.

**Comment by ziadoz** [comment]
@cyanzhong I tried this again and it seems to work for now. I see a QuickLook preview of Markdown files, and the System Settings panel loads properly.

**Comment by formed2forge** [comment]
For me, it was Xcode that was preventing quickview. Once I toggled that off in the Login prefpane for Xcode, MarkEdit's quickview (including the HTML toggle) worked.
