### ISSUE TITLE
[Feature Request] Provide Windows users with an executable file that they can use.

### ISSUE THREAD

**Issue by PShiYou** [MarkEdit-app/MarkEdit#801]
Hello, at first sight of MarkEdit, I was attracted by its simplicity. I have tried many Markdown writing software, but their overly bloated features made me reluctant to use them. Could you package it as an exe file for Windows users? It would be even better if it could offer real-time preview.

**Comment by cyanzhong** [comment]
Thank you for your feedback. Unfortunately, this isn't feasible—porting it to another platform essentially means building a new app.

MarkEdit is not designed as a cross-platform application; over half of its code relies on macOS-specific technologies.

Additionally, I don't use Windows, and I believe it's impossible to create excellent applications for a platform I'm unfamiliar with.
